version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: codershq_local_django
    container_name: django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: codershq_production_postgres
    container_name: postgres
    platform: linux/amd64
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    platform: linux/amd64
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: redis

  celeryworker:
    <<: *django
    image: codershq_local_celeryworker
    container_name: celeryworker
    platform: linux/amd64
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: codershq_local_celerybeat
    container_name: celerybeat
    platform: linux/amd64
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: codershq_local_flower
    container_name: flower
    platform: linux/amd64
    ports:
      - "5555:5555"
    command: /start-flower